# Generated by Django 3.1.4 on 2020-12-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_auto_20201219_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(default='covers/default-cover.png', upload_to='covers'),
        ),
    ]
